### PR TITLE
Uplift Button to be Themeable

### LINKED ISSUE #1038: Uplift Button Component for OCS
# Issue Description
Uplift Button component.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

### LINKED ISSUE #1058: Icon only buttons are not accessible
# Issue Description
Icon only buttons fail accessibility testing.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Passes accessibility tests

## Current Behavior
```
To solve this violation, you need to:
Fix at least one (1) of these issues:
Element has a value attribute and the value attribute is empty
Element has no value attribute or the value attribute is empty
Element does not have inner text that is visible to screen readers
aria-label attribute does not exist or is empty
aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty or not visible
Element's default semantics were not overridden with role="presentation"
Element's default semantics were not overridden with role="none"
And
Fix the following:
Element is in tab order and does not have accessible text
```

## Steps to Reproduce

1. Install [Axe Chrome Extension](https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US)
2. Navigate to the [icon only button example page](http://engineering.cerner.com/terra-core/#/tests/button-tests/icon-only) and the [button group icon example](http://engineering.cerner.com/terra-core/#/tests/button-group-tests/icon-only-button-group)
3. Run axe by going to developer tools and clicking axe tab.

## Environment

* Component Version:
* Browser Name and Version:
* Operating System and version (desktop or mobile):

## Additional Information
Tests that are failing from this are being bypassed with a rule of

```js
  'button-name': { enabled: false },
```
Searching for this should identify all known failed tests in terra.

### PR DESCRIPTION
**Pull request by emilyrohrbough**
### Summary
Closes #1038. Closes #1058. 

#### Adds
- `refCallback`, `isIconOnly`, `onBlur`, `onFocus`, `onKeyDown` and `onKeyUp` props

#### Changes
- `variant` prop options to neutral, emphasis, de-emphasis, action and utility
    - removed primary, secondary, and link
- Enables anchors to trigger href on space

#### Removed
- `isCompact` and `size` props

### NOTES
This PR is almost good to go, just need to add a few more tests, verify some styling for accessibility purposes and add mock theme.

Deployment Link: https://terra-core-deployed-pr-1070.herokuapp.com/static/#/site/button

### CODE REVIEW

File: packages/terra-button/src/Button.jsx [hunk 1]
```diff
@@ -6,105 +6,238 @@ import styles from './Button.scss';
...
+    super(props);
+    this.state = { active: false, focused: false, mouseWasClicked: false };
+    this.handleKeyDown = this.handleKeyDown.bind(this);
+    this.handleKeyUp = this.handleKeyUp.bind(this);
+    this.handleOnBlur = this.handleOnBlur.bind(this);
+  }
+
+  handleOnBlur(event) {
+    this.setState({ focused: false });
+    event.stopPropagation();
```
Comment (mhemesath) [inline packages/terra-button/src/Button.jsx]: generally [stopping propagation is bad](https://css-tricks.com/dangers-stopping-event-propagation/). Why do we need to do this?

File: packages/terra-button/src/Button.scss [hunk 2]
```diff
@@ -54,74 +50,86 @@
...
+    > svg {
+      height: var(--terra-button-icon-height, 1rem);
+      width: var(--terra-button-icon-width, 1rem);
+    }
   }
 
-  .compact {
-    padding-bottom: var(--terra-button-padding-bottom-compact, 0);
-    padding-top: var(--terra-button-padding-top-compact, 0);
+  .icon-only {
```
Comment (mhemesath) [inline packages/terra-button/src/Button.scss]: Is it possible to make the CSS smart enough that we don't need these custom props overrides? These icon-only props are confusing IMO

**Comment by mhemesath** [comment]
Looking at 
image

It looks like the icon isn't vertically centered. Is that right?

**Comment by emilyrohrbough** [comment]
@mhemesath The icon position appears correctly when a true icon is supplied, not a black div

screen shot 2017-12-14 at 9 44 14 am

**Comment by mhemesath** [comment]
>  The icon position appears correctly when a true icon is supplied, not a black div

wondering if we should just pull in terra icons as a dev dependency in button

**Comment by mhemesath** [comment]
I downloaded a browser extension that injects consumer/clinical themes into the page so I can view them. One thing I'm noticing is that components that use buttons don't seem to be getting new theme (e.g. button groups, datepicker). Is that expected?

**Comment by emilyrohrbough** [comment]
@mhemesath Yes this is expected due to this line: https://github.com/cerner/terra-core/pull/1070/files#diff-281a8b5fc2c5518cf832989a55c3c7a0R4. Each button consuming terra-button will need to be uplifted to the newest version. Given the removal of the `isCompact` and `size` prop and changing of the `variant` types, there is potential for lots of updates in the other components.

File: packages/terra-button/tests/wdio/button-spec.js [hunk 3]
```diff
@@ -1,230 +1,298 @@
 /* global browser, Terra, before */
-const ignoreContrast = {
-  'color-contrast': { enabled: false },
+const shouldTheme = (customProperties, selector) => {
```
Comment (yuderekyu) [inline packages/terra-button/tests/wdio/button-spec.js]: When we create the utils package, we could stick this function there for reuse.

File: packages/terra-button/src/Button.scss [hunk 4]
```diff
@@ -54,74 +50,86 @@
       padding: 0;
```
Comment (yuderekyu) [inline packages/terra-button/src/Button.scss]: So firefox automatically adds padding without this set?

File: packages/terra-button/tests/wdio/button-spec.js (hunk 3 above)
Comment (emilyrohrbough) [reply packages/terra-button/tests/wdio/button-spec.js]: This function is actually [already available as a reusable function](https://github.com/cerner/terra-toolkit/blob/master/src/wdio/services/TerraService.js#L69) in the toolkit. We need to enhance this function however to allow one to pass in the selector. Currently it defaults to [data-reactroot] and these tests specify certain butttons.

File: packages/terra-button/src/Button.scss [hunk 5]
```diff
@@ -28,24 +24,24 @@
...
-    padding-left: var(--terra-button-padding-left, 0.714em);
-    padding-right: var(--terra-button-padding-right, 0.714em);
-    padding-top: var(--terra-button-padding-top, 0.286em);
-    text-align: center;
+    font-family: inherit;
+    font-size: inherit;
+    line-height: var(--terra-button-line-height, 1.429);
+    outline: none;
+    padding-bottom: var(--terra-button-padding-bottom, 0.4285rem);
+    padding-left: 0;
```
[the remark this answers is not in the document]
Comment (emilyrohrbough) [reply packages/terra-button/src/Button.scss]: Padding doesn't actually default to 0. In Chrome it appears to give buttons a default padding of 7px to right & left while Safari give a default of 6px right and left

File: packages/terra-button/src/Button.scss (hunk 4 above)
Comment (emilyrohrbough) [reply packages/terra-button/src/Button.scss]: Yeah, Firefox gives focus to the inner elements and will apply two focus rings. This is a screenshot with these styles removed
screen shot 2017-12-15 at 3 30 18 pm

File: packages/terra-button/CHANGELOG.md [hunk 6]
```diff
@@ -3,6 +3,17 @@ Changelog
...
+
+### Added
+* refCallback, isIconOnly, onBlur, onFocus, onKeyDown, onKeyUp props
+
+### Changed
+* text prop is now required for accessibility purposes
+* variant options changes from `primary`, `secondary`, or `link` to `neutral`,  `emphasis`, `de-emphasis`, `utility` or `action`
+
+### Removed
+* size and isCompact props
```
Comment (StephenEsser) [inline packages/terra-button/CHANGELOG.md]: This is just preference, the changed section takes on the role of added and removed so it becomes a little ambiguous. It might be worth considering splitting them out into what was added and what was removed. 

### Added
* refCallback, isIconOnly, onBlur, onFocus, onKeyDown, onKeyUp props
* `neutral`,  `emphasis`, `de-emphasis`, `utility` and `action` variants

### Removed
* size prop
* isCompact prop
* `primary`, `secondary`,  and `link` variants

### Changed
* text prop is now required to meet accessibility

File: packages/terra-button/src/Button.jsx [hunk 7]
```diff
@@ -6,105 +6,238 @@ import styles from './Button.scss';
...
   /**
-   * Sets the button variant. One of `primary`, `secondary`, or `link`
+   * Callback function triggered when key is released.
    */
-  variant: PropTypes.oneOf(['default', 'link', 'primary', 'secondary']),
+  onKeyUp: PropTypes.func,
+  /**
+   *  React `ref` callback to receive and store a reference to the mounted button instance.
+   */
+  refCallback: PropTypes.func,
```
Comment (StephenEsser) [inline packages/terra-button/src/Button.jsx]: We shouldn't need this prop. Making the Button a class should enable the ref callback automatically

File: packages/terra-button/src/Button.jsx [hunk 8]
```diff
@@ -6,105 +6,238 @@ import styles from './Button.scss';
...
+  }
+
+  handleKeyDown(event) {
+    // Add active state to FF browsers
+    if (event.nativeEvent.keyCode === KEYCODES.SPACE) {
+      this.setState({ active: true });
+
+      // Follow href on space keydown when rendered as an anchor tag
+      if (this.props.href) {
+        // Prevent window scrolling
```
Comment (bjankord) [inline packages/terra-button/src/Button.jsx]: What window scrolling is this preventing?

File: packages/terra-button/src/Button.jsx [hunk 9]
```diff
@@ -6,105 +6,238 @@ import styles from './Button.scss';
...
+        {children}
+      </ComponentType>
+    );
+  }
+}
 
 Button.propTypes = propTypes;
 Button.defaultProps = defaultProps;
 
+Button.Opts = { };
```
Comment (bjankord) [inline packages/terra-button/src/Button.jsx]: nit: remove space between brackets.

File: packages/terra-button/src/Button.scss (hunk 4 above)
Comment (bjankord) [reply packages/terra-button/src/Button.scss]: Yeah we need to keep these styles to normalize button styles in Firefox.

File: packages/terra-button/src/Button.jsx (hunk 8 above)
Comment (emilyrohrbough) [reply packages/terra-button/src/Button.jsx]: This is preventing window scroll on space down.

By default, anchor tags will not redirect a user on space down, but I am manually triggering it so the anchor buttons ask like the other button types.

File: packages/terra-site/themeable-variables.json [hunk 10]
```diff
@@ -57,14 +57,111 @@
     "--terra-base-body-margin": "0"
   },
   "Button": {
-    "--terra-button-border-radius": "0.25em",
+    "--terra-button-border-radius": "0.2142rem",
+    "--terra-button-line-height": "1.429",
+    "--terra-button-padding-bottom": "0.4285rem",
```
Comment (neilpfeiffer) [inline packages/terra-site/themeable-variables.json]: update --terra-button-padding-bottom to `0.286rem` to match 4px padding-bottom (probably Zeplin error)

File: packages/terra-button/src/Button.scss [hunk 11]
```diff
@@ -28,24 +24,24 @@
...
-    line-height: 1.429; // 20px when html font size is computed to 14px
-    padding-bottom: var(--terra-button-padding-bottom, 0.286em);
-    padding-left: var(--terra-button-padding-left, 0.714em);
-    padding-right: var(--terra-button-padding-right, 0.714em);
-    padding-top: var(--terra-button-padding-top, 0.286em);
+    font-family: inherit;
+    font-size: inherit;
+    line-height: var(--terra-button-line-height, 1.429);
+    outline: none;
+    padding-bottom: var(--terra-button-vertical-padding, 0.4285rem);
```
Comment (neilpfeiffer) [inline packages/terra-button/src/Button.scss]: update 0.4285rem to `0.286rem` to match 4px padding-top (probably Zeplin error)

Comment (emilyrohrbough) [reply packages/terra-button/src/Button.scss]: I think I missed it while simplifying the theming vars :)

**Comment by neilpfeiffer** [comment]
Tested: PR #1070
Resolves: Issue #1038 and #1058

**Reviewed:**
- Follows pattern considerations documented in Cerner Design Standards: [Buttons](https://wiki.ucern.com/x/I7ulXw)
- Follows UX defined design implementation for Terra-Buttons
- Follows defined theme designs: terra-theme

\
\
Verified by @mndrsn and @neilpfeiffer, Ready for Release.

**Pass** |
-----------|
UX Review|

**Comment by mmalaker** [comment]
Functional verification completed. The button examples display and function correctly.
