### PR TITLE
[terra-button] Fixed focus styles after re-enabling a disabled button.

### LINKED ISSUE #3175: [terra-button] Focus issue after re-enabling a button
# Bug Report

## Description

After disabling a button while it's focused and then re-enabling said button while the focus is on another element, re-enables the button in a focused state, making 2 different elements focused at the same time.

## Steps to Reproduce

1. Set focus on the button, and on button select, set isDisabled property of itself
2. Navigate off from the disabled button to another focusable element
3. Setting said button's isDisabled property to false by mouse click or ENTER button press on the new focusable element
4. The focus is now on both the button and the other element

## Additional Context / Screenshots

Step 0
Step 1
Step 2
Step 3

## Expected Behavior

After disabling the button, the button should lose its focus even after re-enabling said button.

## Possible Solution

The component's focused state is unaffected by the changes in the component's isDisabled property. So, the focused state should be reset when the button becomes disabled.

## Environment

* Component Name and Version: "terra-button": "^3.44.0"
* Browser Name and Version: Google Chrome 85.0.4183.121
* Node/npm Version: [e.g. Node 8/npm 5] Node v10.19.0 / npm 6.14.4
* Webpack Version: "webpack": "^4.30.0"
* Operating System and version (desktop or mobile): Windows 10 Enterprise v1909

### PR DESCRIPTION
**Pull request by saket2403**
### Summary
Updated focused state to be false if isDisabled prop is true.

Closes #3175 

### Deployment Link

https://terra-core-deployed-pr-#.herokuapp.com/

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

**Review by lokesh-0813 — APPROVED** [review]

**Comment by supreethmr** [comment]
we might need to add a test or need to update the existing test to cover this scenario.

File: packages/terra-button/src/Button.jsx [hunk 1]
```diff
@@ -244,7 +244,7 @@ class Button extends React.Component {
         { block: isBlock },
         { compact: isCompact },
         { 'is-active': this.state.active && !isDisabled },
-        { 'is-focused': this.state.focused && !isDisabled },
+        { 'is-focused': this.state.focused && !isDisabled && document.activeElement === this.buttonRef },
```
Comment (ShettyAkarsh) [inline packages/terra-button/src/Button.jsx:247]: should we set the focused state to false when button is set to disabled ?

Comment (saket2403) [reply packages/terra-button/src/Button.jsx]: Updated 8f4df52

**Comment by saket2403** [comment]
> we might need to add a test or need to update the existing test to cover this scenario.

Added wdio test 8f4df52

**Review by ShettyAkarsh — APPROVED** [review]

**Review by pranav300 — APPROVED** [review]

File: packages/terra-button/tests/wdio/button-spec.js [hunk 2]
```diff
@@ -237,4 +237,24 @@ Terra.describeViewports('Button', ['tiny'], () => {
...
+    });
+
+    Terra.it.validatesElement('Button is disabled', { selector: '#root' });
+
+    it('enables button', () => {
+      browser.keys(['Tab']);
+      browser.click('#programmaticDisabledButton2');
+    });
+
+    Terra.it.validatesElement('Enabled Button is not focused', { selector: '#root' });
```
Comment (benbcai) [inline packages/terra-button/tests/wdio/button-spec.js:258]: `Terra.it.validatesElement` is being deprecated. It will be replaced by `Terra.validates.element`.

```suggestion
    it('disables button', () => {
      browser.keys(['Tab']);
      browser.click('#programmaticDisabledButton1');
      Terra.validates.element('Button is disabled', { selector: '#root' });
    });

    it('enables button', () => {
      browser.keys(['Tab']);
      browser.click('#programmaticDisabledButton2');
      Terra.validates.element('Enabled Button is not focused', { selector: '#root' });
    });
```

**Review by benbcai — APPROVED** [review]

**Review by tbiethman — APPROVED** [review]

**Review by jeremyfuksa — APPROVED** [review]
