### PR TITLE
Table - Fix Preselected Row & Test Structure Refactor

### LINKED ISSUE #794: isSelected prop of Table.SingleSelectableRow child not honored without isSelectable
# Issue Description
For terra-table, there are examples of the SingleSelectableRows in the project in test files that show a row as "selected".

```jsx
<Table.SingleSelectableRows>
  <Table.Row isSelected key={'PERSON_0'}>
    <Table.Cell content="John Smith" key="NAME" />
    <Table.Cell content="123 Adams Drive" key="ADDRESS" />
    <Table.Cell content="111-222-3333" key="PHONE_NUMBER" />
  </Table.Row>
</Table.SingleSelectableRows>
```

However, this does not cause any visible change in the UI. It's only when the `isSelectable` property is `true` that `isSelected` is honored. I'm not sure if this is deliberate, but the fact that it shows up in so many tests and in the documentation as having isSelected as being true but having `isSelectable` as `undefined` makes it seem like a bug.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [X] Other

## Expected Behavior
The highlighting of the row should be independent of `isSelectable`. If a row defines `isSelectable` as false, the row could still take `isSelected` as `true`, which would allow the row to be permanently selected. If `isSelectable` is `undefined` on the row, the row should be selectable from the SingleSelectableRows component

## Current Behavior
The row is not highlighted initially when the `isSelected` prop is `true`.

## Side Note
I am also working on contributing a MultipleSelectableRows component. With this component, multiple rows can be selected, but this table should also allow the user to deselect rows. This means that an `isSelectable` prop might not be as appropriate. Something like `isSelectionChangeable` might be more accurate, and could work for both multiple and single.

### PR DESCRIPTION
**Pull request by emilyrohrbough**
### Summary
This PR:
1. Fixed bug to allow for preselected single select table row. Closes #794.
2. Adds nightwatch test for disabled single select table row.
3. Refactors nightwatch tests into `table` and `single-select-table` folders to separate examples and tests. This change mimics the list nightwatch file structure, to make the addition of MultipleSelectRows ( #795 ) tests easier to manage.

### Deployments
1. Preselected Test: https://terra-core-deployed-pr-834.herokuapp.com/static/#/tests/single-select-table-tests/preselected
2. Non-Selectable Test: https://terra-core-deployed-pr-834.herokuapp.com/static/#/tests/single-select-table-tests/non-selectable
3. Refactored Test Links: 
`table` https://terra-core-deployed-pr-834.herokuapp.com/static/#/tests/table-tests & `single-select-table` https://terra-core-deployed-pr-834.herokuapp.com/static/#/tests/single-select-table-tests

### CODE REVIEW

File: packages/terra-table/src/SingleSelectableRows.jsx [hunk 1]
```diff
@@ -31,7 +31,7 @@ class SingleSelectableRows extends React.Component {
     }
     // Find the first row which is selected and is selectable
```
Comment (dkasper-was-taken) [inline packages/terra-table/src/SingleSelectableRows.jsx]: Update this comment to remove selectable.

**Comment by mmalaker** [comment]
Functional verification complete. Table examples and test pages display and function as expected.
