### PR TITLE
[terra-form-textarea] Add first class props to textarea-field from textarea

### LINKED ISSUE #3291: Terra's TextareaField doesn't have the same options exposed as Textarea
# Bug Report

## Description
Specifically, you can't pass size or isAutoResizable

## Steps to Reproduce
1. Look at the docs for each:
https://engineering.cerner.com/terra-ui/components/terra-form-textarea/form-textarea/textarea
https://engineering.cerner.com/terra-ui/components/terra-form-textarea/form-textarea/textarea-field

## Expected Behavior
I would like for textarea-field to have a superset of the options in textarea, with all appropriate ones getting passed to the internal textarea

## Possible Solution
Pass down the relevant props internally?

## Environment
docs

### PR DESCRIPTION
**Pull request by saket2403**
### Summary
Add first class props to textarea-field from textarea.
Closes #3291 

### Deployment Link

https://terra-core-deployed-pr-#.herokuapp.com/

### Testing
Updated jest tests for validating the props.

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

File: packages/terra-form-textarea/src/TextareaField.jsx [hunk 1]
```diff
@@ -112,21 +132,26 @@ const defaultProps = {
   maxWidth: undefined,
   onChange: undefined,
   onInput: undefined,
+  rows: null,
```
Comment (StephenEsser) [inline packages/terra-form-textarea/src/TextareaField.jsx:135]: `null` and `undefined` have slightly different meanings. This should either be unspecified/unlisted from default props or `undefined`

File: packages/terra-form-textarea/src/TextareaField.jsx [hunk 2]
```diff
@@ -83,6 +87,16 @@ const propTypes = {
...
+  /**
+   * Value to set for the rows attribute of the textarea. This takes precedence over size when
+   * setting the height of the textarea.
+   */
+  rows: PropTypes.number,
+  /**
+   * The size of the textarea. _(Sizes the textarea by setting the rows attribute a corresponding preset value.)_
+   */
+  size: PropTypes.oneOf(['small', 'medium', 'large', 'full']),
+
```
Comment (StephenEsser) [inline packages/terra-form-textarea/src/TextareaField.jsx:99]: nit: extra space

File: packages/terra-form-textarea/CHANGELOG.md [hunk 3]
```diff
@@ -2,6 +2,9 @@
 
 ## Unreleased
 
+* Fixed
+ * Added similar props from textarea to textarea-field.
```
Comment (emilyrohrbough) [inline packages/terra-form-textarea/CHANGELOG.md:6]: Could you expand on this?

File: packages/terra-form-textarea/src/TextareaField.jsx [hunk 4]
```diff
@@ -181,12 +208,16 @@ const TextareaField = (props) => {
         {...inputAttrs}
         disabled={inputAttrs.disabled || disabled}
         id={inputId}
+        isAutoResizable={isAutoResizable}
```
Comment (StephenEsser) [inline packages/terra-form-textarea/src/TextareaField.jsx:211]: We might need to back patch each of these similar to `disabled={inputAttrs.disabled || disabled}` above to remain passive. Otherwise anyone previously using `inputAttrs` to set these values would be overwritten.

A quick test would be to create an example using inputAttrs and see if the values are overwritten:

```jsx
// Does this still work after these changes?
<TextareaField inputAttrs={{ isAutoResizable: true }} />
```

File: packages/terra-form-textarea/src/TextareaField.jsx (hunk 1 above)
Comment (saket2403) [reply packages/terra-form-textarea/src/TextareaField.jsx]: Setting default value to undefined made similar change in textarea also ca966a9.

File: packages/terra-form-textarea/src/TextareaField.jsx (hunk 2 above)
Comment (saket2403) [reply packages/terra-form-textarea/src/TextareaField.jsx]: Removed ca966a9

File: packages/terra-form-textarea/CHANGELOG.md (hunk 3 above)
Comment (saket2403) [reply packages/terra-form-textarea/CHANGELOG.md]: Changed ca966a9

File: packages/terra-form-textarea/src/TextareaField.jsx (hunk 4 above)
Comment (saket2403) [reply packages/terra-form-textarea/src/TextareaField.jsx]: Changed for all new props ca966a9

**Review by emilyrohrbough — APPROVED** [review]

**Review by StephenEsser — APPROVED** [review]

**Review by mjhenkes — APPROVED** [review]
