### PR TITLE
Fix wdio timeouts

### LINKED ISSUE #1216: Tabs webdriver tests timeout
# Issue Description
Tabs seems to be frequently timeout out during wdio tests. Need to look into this and figure out a fix for the timeout issue.

### PR DESCRIPTION
**Pull request by JakeLaCombe**
### Summary
Resolves #1216 WDIO tests are timing out. While looking through the tests, the tabs did a double for loop of rendering the same screenshots. You can see the original code here. 

https://github.com/cerner/terra-core/blob/master/packages/terra-tabs/tests/wdio/tabs-spec.js#L41

To fix it, we just take a screenshot of the current viewport the test is currently running at.

### CODE REVIEW

**Comment by JakeLaCombe** [comment]
I also looked at the screenshots produced, and verified that it's the same number of screenshots as well as the same content as before.

File: packages/terra-tabs/tests/wdio/tabs-spec.js [hunk 1]
```diff
@@ -15,26 +15,26 @@ describe('Tabs - Responsive', () => {
         browser.setViewportSize(viewport);
         browser.moveToObject('.tabContent');
       });
-      Terra.should.matchScreenshot({ viewports });
-      Terra.should.beAccessible({ viewports });
+      Terra.should.matchScreenshot();
+      Terra.should.beAccessible({ viewports: [viewport] });
```
Comment (emilyrohrbough) [inline packages/terra-tabs/tests/wdio/tabs-spec.js]: Actually this an be updated to be `Terra.should.beAccessible();`
By not passing a viewport, it uses the current viewport size (which is set in the loop above).

Comment (bjankord) [reply packages/terra-tabs/tests/wdio/tabs-spec.js]: Interesting, we should get this updated before we merge.
