### PR TITLE
[terra-profile-image] Removed container div.

### LINKED ISSUE #3412: [terra-profile-image] Placeholder image seems to have extra space in its div
# Bug Report

## Description

This problem was discovered in demographics banner, during loading of a profile image, there was a slight difference in size of the banner between showing placeholder image and showing the desired image. Upon inspection of the documentation at https://engineering.cerner.com/terra-ui/components/terra-profile-image/profile-image/profile-image it appears to happen there as well.

## Steps to Reproduce

1. Navigate to https://engineering.cerner.com/terra-ui/components/terra-profile-image/profile-image/profile-image
2. Inspect divs around Successful Profile Image and Failed Profile Image and compare the heights of the divs
3.
4.

## Additional Context / Screenshots

image
image

## Expected Behavior

I would expect both images to have the same size so that things like the demographics banner does not resize upon loading.

## Environment

* Component Name and Version: terra-profile-image
* Browser Name and Version: Google Chrome Version 89.0.4389.90 (Official Build) (x86_64)
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile): MacOS Catalina 10.15.7

### PR DESCRIPTION
**Pull request by pranav300**
### Summary

This PR removes the extra space being consumed by profile-image's div.

Closes #3412 

### Deployment Link

https://terra-core-deployed-pr-#.herokuapp.com/

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

File: packages/terra-profile-image/src/ProfileImage.jsx [hunk 1]
```diff
@@ -63,7 +63,7 @@ const ProfileImage = (props) => {
   /* eslint-enable react/forbid-dom-props */
 
   if (props.src) {
-    return (<div><TerraImage placeholder={placeholderImage} {...props} /></div>);
+    return (<div className={cx('image-container')}><TerraImage placeholder={placeholderImage} {...props} /></div>);
```
Comment (yuderekyu) [inline packages/terra-profile-image/src/ProfileImage.jsx:66]: what happens if we remove the div altogether?

Comment (pranav300) [reply packages/terra-profile-image/src/ProfileImage.jsx]: That also fixes the issue. Updated it here https://github.com/cerner/terra-core/pull/3422/commits/5e756c9c6a21ba93d3bc8ca99d0590da5e3cb10e.

**Review by mjhenkes — APPROVED** [review]

**Review by yuderekyu — APPROVED** [review]

**Review by supreethmr — APPROVED** [review]

**Review by benbcai — APPROVED** [review]

**Review by lokesh-0813 — APPROVED** [review]

**Review by ShettyAkarsh — APPROVED** [review]

**Review by neilpfeiffer — APPROVED** [review]
Tested: PR #3422
Resolves: Issue #3412

**Reviewed:**
- fixes the immediate issue of inconsistency in dimension size between the valid image src and an invalid image and fallback placeholder built-in
- additional testing shows that there are other problems with the placeholder image that this does not resolve, logging this new issue #3432 to resolve as followup.


 **UX Reviewed** |
-----------|
