### PR TITLE
Arrange component fix

### LINKED ISSUE #172: Arrange: Fit End Alignment Stretch
Stretch behavior differs between Chrome and Safari. The fit end alignment is set to `stretch` in both examples.

**Chrome**
screen shot 2017-03-27 at 1 08 34 pm

**Safari** (desktop and mobile)
screen shot 2017-03-27 at 1 07 20 pm

### PR DESCRIPTION
**Pull request by bjankord**
### Summary
* Added nightwatch tests for arrange.
* Fixed issue in Safari where children elements within `fitStart` and `fitEnd` that used `alignFitStart="stretch"` / `alignFitEnd="stretch"` / `align="stretch"` did not fill height of `fitStart` /  `fitEnd` container.

Fixes #172 

Thanks for contributing to Terra. 
@cerner/terra

[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md
[License]: ../blob/master/LICENSE

### CODE REVIEW

File: packages/terra-arrange/tests/nightwatch/arrange-spec.js [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+
+module.exports = {
+  before: (browser, done) => {
+    browser.resizeWindow(browser.globals.width, browser.globals.height, done);
+  },
+
+  afterEach: (browser, done) => {
+    screenshot(browser, 'terra-base', done);
+  },
+
```
Comment (jmsv6d) [inline packages/terra-arrange/tests/nightwatch/arrange-spec.js]: You need to add tests here so that all the screenshots will be generated.

File: packages/terra-arrange/tests/nightwatch/arrange-spec.js [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+const screenshot = require('terra-toolkit').screenshot;
+
+module.exports = {
+  before: (browser, done) => {
+    browser.resizeWindow(browser.globals.width, browser.globals.height, done);
+  },
+
+  afterEach: (browser, done) => {
+    screenshot(browser, 'terra-base', done);
```
Comment (jmsv6d) [inline packages/terra-arrange/tests/nightwatch/arrange-spec.js]: The string here should be 'terra-arrange'

File: packages/terra-arrange/package.json [hunk 3]
```diff
@@ -45,6 +45,7 @@
     "terra-mixins": "^1.0.0"
   },
   "devDependencies": {
-    "terra-toolkit": "^0.x"
+    "terra-toolkit": "^0.x",
+    "terra-icon": "^0.x"
   }
 }
```
Comment (jmsv6d) [inline packages/terra-arrange/package.json]: The nightwatch test scripts need to be added in here.
Example: https://github.com/cerner/terra-core/blob/master/packages/terra-button/package.json#L36

Comment (bjankord) [inline packages/terra-arrange/package.json]: Updated: https://github.com/cerner/terra-core/pull/220/commits/81d1a25e63ec33a13af6ea97df4ef3f9d26c1e16

File: packages/terra-arrange/tests/nightwatch/arrange-spec.js (hunk 1 above)
Comment (bjankord) [inline packages/terra-arrange/tests/nightwatch/arrange-spec.js]: Updated: https://github.com/cerner/terra-core/pull/220/commits/6ffb3a61c4409e7bf36cd8bbb5d159b2b2006bb1

File: packages/terra-arrange/tests/nightwatch/arrange-spec.js (hunk 2 above)
Comment (bjankord) [inline packages/terra-arrange/tests/nightwatch/arrange-spec.js]: Updated: https://github.com/cerner/terra-core/pull/220/commits/6ffb3a61c4409e7bf36cd8bbb5d159b2b2006bb1

File: packages/terra-arrange/package.json [hunk 4]
```diff
@@ -31,8 +31,15 @@
     "release:major": "npm test && node ../../scripts/release/release.js major",
     "release:minor": "npm test && node ../../scripts/release/release.js minor",
     "release:patch": "npm test && node ../../scripts/release/release.js patch",
-    "test": "npm run test:spec",
-    "test:spec": "$(cd ..; npm bin)/jest --config ../../jestconfig.json"
+    "test": "npm run test:spec && npm run test:nightwatch-default",
+    "test:spec": "$(cd ..; npm bin)/jest --config ../../jestconfig.json",
+    "test:all": "npm run test:nightwatch-default && npm run test:nightwatch-chrome && npm run test:nightwatch-firefox && npm run test:nightwatch-safari",
+    "test:nightwatch-default": "SPECTRE_TEST_SUITE=terra-button node ./node_modules/terra-toolkit/lib/scripts/nightwatch.js",
```
Comment (jmsv6d) [inline packages/terra-arrange/package.json]: These need to be SPECTRE_TEST_SUITE=terra-arrange

Comment (bjankord) [inline packages/terra-arrange/package.json]: Ah good catch, I missed that. Updated: https://github.com/cerner/terra-core/pull/220/commits/40e7a9db165be4a25b3414381d07742828c9f2ea
