### PR TITLE
[form-input] Added ariaLabel prop Part-2

### LINKED ISSUE #2570: [axe-core-warning] Ensures every form element has a label
# Bug Report
Accessibility is violated on a few TextArea test pages and had a consumer tell me that they ran into this issue while running their _wdio_ tests as well.

<details>
 <summary>WDIO Axe Error Report</summary>

```
"description": "Ensures every form element has a label",
  "help": "Form elements must have labels",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/label?application=axeAPI",
  "id": "label",
  "impact": "critical",
  "nodes": [
    {
      "all": [],
      "any": [
        {
          "data": null,
          "id": "aria-label",
          "impact": "serious",
          "message": "aria-label attribute does not exist or is empty",
          "relatedNodes": []
        },
        {
          "data": null,
          "id": "aria-labelledby",
          "impact": "serious",
          "message": "aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty",
          "relatedNodes": []
        },
        {
          "data": null,
          "id": "implicit-label",
          "impact": "critical",
          "message": "Form element does not have an implicit (wrapped) <label>",
          "relatedNodes": []
        },
        {
          "data": null,
          "id": "explicit-label",
          "impact": "critical",
          "message": "Form element does not have an explicit <label>",
          "relatedNodes": []
        },
        {
          "data": null,
          "id": "non-empty-title",
          "impact": "serious",
          "message": "Element has no title attribute or the title attribute is empty",
          "relatedNodes": []
        }
      ],
      "failureSummary": "Fix any of the following:\n  aria-label attribute does not exist or is empty\n  aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty\n  Form element does not have an implicit (wrapped) <label>\n  Form element does not have an explicit <label>\n  Element has no title attribute or the title attribute is empty",
      "html": "<textarea id=\"auto-resizable\" cols=\"2\" rows=\"2\" class=\"Textarea-module__textarea___2LAQp\" style=\"min-height: 48px; caret-color: transparent;\">Default Value</textarea>",
      "impact": "critical",
      "none": [],
      "target": [
        "#auto-resizable"
      ]
    }
  ],
  "tags": [
    "cat.forms",
    "wcag2a",
    "wcag332",
    "wcag131",
    "section508",
    "section508.22.n"
  ]

```
</details>

## Steps to Reproduce

1. Go to https://engineering.cerner.com/terra-core/tests/terra-form-textarea/form-textarea/auto-resizable-textarea
2. Run the axe test.

### Additional Information
It looks like the rule is being ignored in the _wdio_ tests [1] for TextArea. Is this for a reason?

[1] https://github.com/cerner/terra-core/blob/21630dbf90a05bb93567aeba3a687843ad142246/packages/terra-form-textarea/tests/wdio/form-textarea-spec.js#L1-L3

### PR DESCRIPTION
**Pull request by pranav300**
### Summary
Added `ariaLabel` prop to improve accessibility.
Partially resolves #2570

### CODE REVIEW

File: packages/terra-form-fieldset/src/terra-dev-site/doc/example/FieldsetExamples.jsx [hunk 1]
```diff
@@ -46,18 +46,18 @@ class FieldsetExamples extends React.Component {
           required
         >
           <Field label="First" isInline required htmlFor="first">
```
Comment (bjankord) [inline packages/terra-form-fieldset/src/terra-dev-site/doc/example/FieldsetExamples.jsx]: Let's use the same label as the label in the field. In this case, the label would be `First`

File: packages/terra-form-input/src/terra-dev-site/doc/common/BlankExample.jsx [hunk 2]
```diff
@@ -5,7 +5,7 @@ import Input from '../../../Input';
 const BlankExample = () => (
   <div>
     <Field label="Blank" htmlFor="blank">
-      <Input name="default blank input" id="blank" />
+      <Input name="default blank input" id="blank" ariaLabel="form-input-label" />
```
Comment (bjankord) [inline packages/terra-form-input/src/terra-dev-site/doc/common/BlankExample.jsx]: Let's update the ariaLabel value so it matches the label value on the `<Field />` component. e.g.:  `ariaLabel="Blank"`

File: packages/terra-form-input/src/terra-dev-site/doc/example/controlled/DefaultExample.jsx [hunk 3]
```diff
@@ -17,12 +17,12 @@ class DefaultExample extends React.Component {
...
     return (
       <div>
-        <Field label="Default" htmlFor="default-controlled">
+        <Field label="Default">
           <Input
             name="default input"
-            id="default-controlled"
             value={this.state.input}
             onChange={this.handleChange}
+            ariaLabel="form-input-label"
```
Comment (bjankord) [inline packages/terra-form-input/src/terra-dev-site/doc/example/controlled/DefaultExample.jsx]: Let's update this to the following:
```suggestion
            ariaLabel="Default"
```

File: packages/terra-form-input/src/terra-dev-site/doc/example/uncontrolled/DefaultExample.jsx [hunk 4]
```diff
@@ -4,11 +4,11 @@ import Input from 'terra-form-input';
 
 const DefaultExample = () => (
   <div>
-    <Field label="Default" htmlFor="uncontrolled-default">
+    <Field label="Default">
       <Input
         name="default input"
-        id="uncontrolled-default"
         defaultValue="Default Input – Uncontrolled"
+        ariaLabel="form-input-label"
```
Comment (bjankord) [inline packages/terra-form-input/src/terra-dev-site/doc/example/uncontrolled/DefaultExample.jsx]: Let's update this to the following:
```suggestion
        ariaLabel="Default"
```

**Comment by bjankord** [comment]
@pranav300 I'm planning to pick up this PR and address the comments I had so we can get this merged in for today's release.

**Comment by bjankord** [comment]
There is an axe error with this being generated from the search field component:
Posted details from error output below:

<details>

<summary>Error Output</summary>

```
1) [medium] Search Field Default [empty] is accessible and is within the mismatch tolerance:
expected no accessibility violations but got:
	{
  "description": "Ensures every form element has a label",
  "help": "Form elements must have labels",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/label?application=axeAPI",
  "id": "label",
  "impact": "critical",
  "nodes": [
    {
      "all": [],
      "any": [
        {
          "data": null,
          "id": "aria-label",
          "impact": "serious",
          "message": "aria-label attribute does not exist or is empty",
          "relatedNodes": []
        },
        {
          "data": null,
          "id": "aria-labelledby",
          "impact": "serious",
          "message": "aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty",
          "relatedNodes": []
        },
        {
          "data": null,
          "id": "implicit-label",
          "impact": "critical",
          "message": "Form element does not have an implicit (wrapped) <label>",
          "relatedNodes": []
        },
        {
          "data": null,
          "id": "explicit-label",
          "impact": "critical",
          "message": "Form element does not have an explicit <label>",
          "relatedNodes": []
        },
        {
          "data": null,
          "id": "non-empty-title",
          "impact": "serious",
          "message": "Element has no title attribute or the title attribute is empty",
          "relatedNodes": []
        }
      ],
      "failureSummary": "Fix any of the following:\n  aria-label attribute does not exist or is empty\n  aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty\n  Form element does not have an implicit (wrapped) <label>\n  Form element does not have an explicit <label>\n  Element has no title attribute or the title attribute is empty",
      "html": "<input class=\"Input-module__form-input___1P2d6 SearchField-module__input___1WL41\" placeholder=\"\" aria-disabled=\"false\" type=\"search\" value=\"\">",
      "impact": "critical",
      "none": [],
      "target": [
        "input"
      ]
    }
  ],
  "tags": [
    "cat.forms",
    "wcag2a",
    "wcag332",
    "wcag131",
    "section508",
    "section508.22.n"
  ]
}
```

<details>

File: packages/terra-search-field/CHANGELOG.md [hunk 5]
```diff
@@ -21,6 +23,7 @@ Unreleased
 * Components updated to use `injectIntl` to interface with `react-intl's` `intl` context.
 * Update jest test snapshot
 * updated package.json test scripts
+* updated source and jest files for changes in form-input
```
Comment (bjankord) [inline packages/terra-search-field/CHANGELOG.md]: This line can be removed, we have it listed already under the `### Changed` section under the `Unreleased` section.

File: packages/terra-search-field/src/SearchField.jsx [hunk 6]
```diff
@@ -254,6 +254,7 @@ class SearchField extends React.Component {
             placeholder={placeholder}
             onChange={this.handleTextChange}
             disabled={isDisabled}
+            ariaLabel={inputText}
```
Comment (bjankord) [inline packages/terra-search-field/src/SearchField.jsx]: If users set a custom aria-label via `<SearchField inputAttributes={{'aria-label': 'Custom aria label'}} />`, we'll want to pass that down to the `<Input />` component's `ariaLabel` prop.

We can update this line:
```
const inputText = intl.formatMessage({ id: 'Terra.searchField.search' });
```
to use the translation fallback if `aria-label` is not set via `inputAttributes` prop and then pass inputText as you have it on line 257.

Something like:
```
const inputText = inputAttributes.hasOwnProperty('aria-label') ? inputAttributes['aria-label'] : intl.formatMessage({ id: 'Terra.searchField.search' }); 
```

File: packages/terra-search-field/tests/jest/SearchField.test.jsx [hunk 7]
```diff
@@ -46,7 +46,7 @@ describe('Snapshots', () => {
   });
 
   it('renders a search field with an aria-label', () => {
-    const searchField = shallowWithIntl(<SearchField inputAttributes={{ 'aria-label': 'Search Field' }} />).dive();
+    const searchField = shallowWithIntl(<SearchField inputAttributes={{ ariaLabel: 'Search Field' }} />).dive();
```
Comment (bjankord) [inline packages/terra-search-field/tests/jest/SearchField.test.jsx]: We'll want this to still work with `inputAttributes={{ 'aria-label': 'Search Field'}}`, otherwise this becomes a breaking change. Consumers may be using this syntax to set custom aria-labels.

We'll also now need to support `inputAttributes={{ 'ariaLabel': 'Search Field'}}`

File: packages/terra-search-field/src/SearchField.jsx [hunk 8]
```diff
@@ -220,10 +220,12 @@ class SearchField extends React.Component {
       customProps.className,
     ]);
 
-    const inputText = intl.formatMessage({ id: 'Terra.searchField.search' });
+    // eslint-disable-next-line no-prototype-builtins
+    const inputText = inputAttributes && inputAttributes.hasOwnProperty('aria-label') ? inputAttributes['aria-label'] : intl.formatMessage({ id: 'Terra.searchField.search' });
```
Comment (bjankord) [inline packages/terra-search-field/src/SearchField.jsx]: Let's try this and remove the eslint-disable comment:
```suggestion
    const inputText = inputAttributes && Object.prototype.hasOwnProperty.call(inputAttributes, 'aria-label') ? inputAttributes['aria-label'] : intl.formatMessage({ id: 'Terra.searchField.search' });
```

Comment (pranav300) [reply packages/terra-search-field/src/SearchField.jsx]: fixed here https://github.com/cerner/terra-core/pull/2587/commits/9ff4a13924754de046bea15ec89ec3056de74478.
