### PR TITLE
[terra-paginator] Fixed  focus issue in Paginator Button when navigating via keyboard.

### LINKED ISSUE #3429: [terra-paginator] Multiple UI elements are in focus
# Bug Report
Both the <Previous and Next> buttons are outlined as focused, but only one should have the focus.

## Description

Both the <Previous and Next> buttons are outlined as focused.
multiple-focus
multiple-item-focused

## Steps to Reproduce

multiple-focus
1. Open the https://engineering.cerner.com/terra-ui/components/terra-paginator/paginator/progressive-paginator-controlled
page
2. Go to the penultimate page (page 44) by mouse clicks.
3. Press Tab until the "Next" button is selected
4. Click on the focused Next button
5. Press Shift + Tab, the focus will be on the Previous button.
6. Press enter or click on the Previous button.

## Expected Behavior

Only the Previous button should have the outlined focus. The re-enabled Next button should lose focus.

## Environment

* Component Name and Version: terra-paginator/lib/ControlledProgressivePaginator 2.72.0
* Browser Name and Version: Chrome, Version 90.0.4430.93
* Node/npm Version: N/A
* Webpack Version: N/A
* Operating System and version (desktop or mobile): Windows 10 desktop

### PR DESCRIPTION
**Pull request by pranav300**
### Summary

This PR updates the `useEffect` hook in `PaginatorButton` to set focus as `false` when it is `disabled`.
 

Closes #3429 

### Deployment Link

https://terra-core-deployed-pr-#.herokuapp.com/

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

**Review by lokesh-0813 — APPROVED** [review]

**Review by supreethmr — APPROVED** [review]

**Comment by benbcai** [comment]
Can we add a test step to test this change?

**Review by benbcai — APPROVED** [review]

File: packages/terra-paginator/tests/wdio/paginator-spec.js [hunk 1]
```diff
@@ -125,4 +125,20 @@ Terra.describeViewports('Controlled Paginator', ['large'], () => {
...
+    });
+
+    it('should navigate to previous button and enter', () => {
+      browser.keys(['Shift', 'Tab', 'Shift', 'Enter']);
+    });
+
+    it('should navigate back to next button and enter', () => {
+      browser.keys(['Tab', 'Enter']);
+      Terra.validates.element('previous button is not focused');
+    });
```
Comment (yuderekyu) [inline packages/terra-paginator/tests/wdio/paginator-spec.js:142]: this might be nitpicky, but these first two it blocks are really setup for the actual test assertion. My vote is to convert these into a single it block. We could add a comment before each `browser.keys` to specify what setup we are doing. I'm curious what you think?

Comment (yuderekyu) [reply packages/terra-paginator/tests/wdio/paginator-spec.js]: oops, I should have specified that I was thinking we could combine them into the last it block that does the `Terra.validates` call. Not a big deal tho

**Review by yuderekyu — APPROVED** [review]

File: packages/terra-paginator/tests/wdio/paginator-spec.js (hunk 1 above)
Comment (pranav300) [reply packages/terra-paginator/tests/wdio/paginator-spec.js]: I will do that.

Comment (pranav300) [reply packages/terra-paginator/tests/wdio/paginator-spec.js]: Update here https://github.com/cerner/terra-core/pull/3438/commits/8058e9b945f88eba76a1ceed0b8f2b71dadd6a08

**Review by mjhenkes — APPROVED** [review]
