### PR TITLE
[terra-image] Leverage react fragment to prevent double requests from…

### LINKED ISSUE #2757: [terra-image] Two img requests made when placeholder prop is provided
# Bug Report

## Description
Two requests for the image src are made by terra-image when the placeholder prop is provided instead of one.

## Steps to Reproduce
1. Launch our single page application (PowerChart Touch) in DEVENG in chrome
2. Open chrome network tools and navigate to any given patient's chart.
3. Notice how two requests for the patient thumbnail are sent instead of one.

## Expected Behavior
Only one request to be made.

## Possible Solution
The issue is occurring as the img tag for the placeholder state is recreated by react once it has loaded. The solution I found was to wrap the img tag in the render function of terra-image in a div such that the structure is similar to what is rendered during the during the placeholder state lifecycle.

## Environment

* Component Name and Version:
* Browser Name and Version: Chrome
* Node/npm Version: [8.16.2/6.4.1]
* Webpack Version: 4.41.2
* Operating System and version (desktop or mobile): Mac OSX

### PR DESCRIPTION
**Pull request by jeffmerten**
… occuring

### Summary
Use React Fragment to wrap placeholder and image in order to prevent the img request from happening twice.

### Additional Details
Previously the img element would be created twice as it was in a div structure that changed when the state changed to on the initial image load. The re-render would cause a new img element to be created. 

The fix is to wrap the img element in react fragment so it doesn't get recreated by react.

The change has been tested by myself in one of our single page applications for our demographics thumbnail image.

Closes #2757

### CODE REVIEW

File: packages/terra-image/src/Image.jsx [hunk 1]
```diff
@@ -143,28 +143,35 @@ class Image extends React.Component {
...
       objectFitImages(this.ImageRef.current);
     }
     if (placeholder) {
       if (this.state.isLoading) {
         return (
-          <div>
-            <div className={cx('hidden')}>{this.createImage(customProps, imageClasses)}</div>
-            <div>{placeholder}</div>
-          </div>
+          <React.Fragment>
```
Comment (yuderekyu) [inline packages/terra-image/src/Image.jsx]: nitpick, can we use shorthand instead? `<>`

Comment (jeffmerten) [reply packages/terra-image/src/Image.jsx]: I kind of prefer React.Fragment since it's easier on my old man eyes, but I'll go with the shorthand since you guys are gonna maintain terra-image more than I going forward.

File: packages/terra-image/src/Image.jsx [hunk 2]
```diff
@@ -143,28 +143,35 @@ class Image extends React.Component {
...
-          </div>
+          <>
+            {this.createImage(customProps, imageClasses)}
+            {placeholder}
+          </>
         );
       }
 
-      return this.state.isError ? placeholder : this.createImage(customProps, imageClasses);
+      return this.state.isError ? placeholder : <>{this.createImage(customProps, imageClasses)}</>;
```
Comment (tbiethman) [inline packages/terra-image/src/Image.jsx]: Is the fragment here necessary?

Comment (jeffmerten) [reply packages/terra-image/src/Image.jsx]: Nope, was just being safe with my initial fix. Just tested without it and works.

File: packages/terra-image/src/Image.jsx [hunk 3]
```diff
@@ -143,24 +143,31 @@ class Image extends React.Component {
...
     } = this.props;
 
-    const imageClasses = cx([
+    const imageClassAttributes = [
       'image',
       fit,
       variant,
       customProps.className,
       { fluid: isFluid },
-    ]);
```
Comment (emilyrohrbough) [inline packages/terra-image/src/Image.jsx]: Can you add like:

```diff
   const imageClasses = cx([
      'image',
      fit,
      variant,
      customProps.className,
      { fluid: isFluid },
+     { hidden: placeholder && this.state.isLoading }
    ]);

```

Comment (jeffmerten) [reply packages/terra-image/src/Image.jsx]: I had something like this initially but decided against it as I didn't want to collide with the custom attributes a consumer could provide after the image had loaded.

Comment (jeffmerten) [reply packages/terra-image/src/Image.jsx]: Let me know if you think this is a valid concern or not. From the way our team uses terra-image/profile-image it wouldn't affect us at all, and I'm sure anyone applying a hidden attribute to terra-image for some odd use case could find a work around.

Comment (jeffmerten) [reply packages/terra-image/src/Image.jsx]: Nevermind, didn't know classNames removes falsy values.

Comment (emilyrohrbough) [reply packages/terra-image/src/Image.jsx]: yeah it removes falsey values! It's great 😄

**Comment by mjhenkes** [comment]
Thanks @jeffmerten :)
