### PR TITLE
[terra-form-select][terra-dropdown-button] Fix to prevent modal from closing on pressing escape to close select

### LINKED ISSUE #3148: [terra-form-select] Escaping out of a terra-form-select will close out of an escape-closable modal
# Bug Report

## Description

When you use escape to close a select inside of a modal that can also be closed using escape, it closes the modal instead of just the select

## Expected Behavior

Only the select closes.

## Possible Solution

Potentially this could be fixed by just stopping event propagation.

## @ Mentions

@StephenEsser

### PR DESCRIPTION
**Pull request by saket2403**
### Summary

Once this PR is merged another PR will be opened for abstract modal for preventing modal to close on pressing escape to close the select and dropdown button
Closes #3148 
### Deployment Link

https://terra-core-select-propa-pe4koa.herokuapp.com/

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

File: packages/terra-form-select/src/combobox/Frame.jsx [hunk 1]
```diff
@@ -381,6 +381,10 @@ class Frame extends React.Component {
   handleKeyDown(event) {
     const { keyCode, target } = event;
 
+    if (this.state.isOpen) {
+      event.stopPropagation();
```
Comment (emilyrohrbough) [inline packages/terra-form-select/src/combobox/Frame.jsx:385]: do we always want to stop propagation if the select is open or only when the escape key is closed?

Comment (saket2403) [reply packages/terra-form-select/src/combobox/Frame.jsx]: Done cac04d4

**Review by emilyrohrbough — APPROVED** [review]

**Review by supreethmr — APPROVED** [review]

**Review by ShettyAkarsh — APPROVED** [review]

**Review by tbiethman — APPROVED** [review]

**Review by pranav300 — APPROVED** [review]

**Review by avinashg1994 — APPROVED** [review]

**Comment by PaulSolDev** [comment]
Functional review complete. No issues identified.

**Review by lokesh-0813 — APPROVED** [review]
