### PR TITLE
[terra-search-field] Add data-attribute for the clear and search button.

### LINKED ISSUE #3206: [terra-search-field] Add data attribute for clear button.
# Bug Report

## Description

We must add data-attribute for the clear button, to make it easily accessible for testing.

### PR DESCRIPTION
**Pull request by pranav300**
### Summary

Added data-attribute `data-terra-search-field-button="Clear" and `data-terra-search-field-button="Search"`` for the clear and search button.

Closes #3206 

### Deployment Link

https://terra-core-deployed-pr-#.herokuapp.com/

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

File: packages/terra-search-field/tests/wdio/search-field-spec.js [hunk 1]
```diff
@@ -68,12 +68,13 @@ Terra.describeViewports('Search Field', ['medium'], () => {
...
-    it('should enter a new search term', () => {
-      browser.click('input');
-      for (let i = 0; i < 7; i += 1) {
-        browser.keys('Backspace');
-      }
+    it('should clear the value', () => {
+      browser.click('#searchfield [data-terra-search-field-button="Clear"]');
+    });
+
+    Terra.it.validatesElement('Clear');
```
Comment (saket2403) [inline packages/terra-search-field/tests/wdio/search-field-spec.js:75]: Terra.it helpers are getting deprecated, use `Terra.validates.element()` inside the it block.

File: packages/terra-search-field/src/SearchField.jsx [hunk 2]
```diff
@@ -265,6 +265,7 @@ class SearchField extends React.Component {
     const clearButton = this.searchText && !isDisabled
       ? (
         <Button
+          data-terra-search-field-button="Clear"
```
Comment (emilyrohrbough) [inline packages/terra-search-field/src/SearchField.jsx:268]: While we are in here, we should add `data-terra-search-field-button="Search"` to the search button as well

Comment (emilyrohrbough) [reply packages/terra-search-field/src/SearchField.jsx:268]: We should also add docs on these data attributes since they were added for testing. Here's an example of how this might look: https://engineering.cerner.com/terra-ui/components/terra-notification-dialog/notification-dialog/notification-dialog#testing

File: packages/terra-search-field/tests/wdio/search-field-spec.js (hunk 1 above)
Comment (pranav300) [reply packages/terra-search-field/tests/wdio/search-field-spec.js]: updated here https://github.com/cerner/terra-core/pull/3207/commits/3719667d69adc3eef032db7b37867b2ee9c928ed

File: packages/terra-search-field/src/SearchField.jsx (hunk 2 above)
Comment (pranav300) [reply packages/terra-search-field/src/SearchField.jsx:268]: Added here https://github.com/cerner/terra-core/pull/3207/commits/3719667d69adc3eef032db7b37867b2ee9c928ed

**Review by emilyrohrbough — APPROVED** [review]

**Review by saket2403 — APPROVED** [review]

**Review by supreethmr — APPROVED** [review]

**Review by ryanthemanuel — APPROVED** [review]
