### PR TITLE
Fix onChange Callback for Time Input

### LINKED ISSUE #536: No OnChange Callback on KeyDown Changes
# Issue Description
Users have the ability to change the time input by manually inputing time or using the keyboard arrows. When the keyboard errors are used to change the time, there is no onChange check or callback occurring.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
On any input change, the onChange prop is checked and called if appropriate.

## Current Behavior
Currently we are not checking for `this.props.onChange` within the `handleInputKeyDown` function. Added these lines after setting the state would fix the issue.

```
    if (this.props.onChange) {
      let enteredTime;
      if (type === inputType.HOUR) {
        enteredTime = stateValue.concat(':', this.state.minute);
      } else {
        enteredTime = this.state.hour.concat(':', stateValue);
      }

      this.props.onChange(event, enteredTime);
    }
```

### PR DESCRIPTION
**Pull request by emilyrohrbough**
### Summary
Fixed when onChange callback occurs such that the onChange is triggered for input changes from the up and down arrows and onBlur changes. Previously, onChange only occurred for numeric key entry. Resolves #536 

@cerner/terra

### CODE REVIEW

File: packages/terra-time-input/tests/nightwatch/component/TimeInputOnChange.jsx [hunk 1]
```diff
@@ -0,0 +1,30 @@
+import React from 'react';
+import TimeInput from '../../../src/TimeInput';
```
Comment (Matt-Butler) [inline packages/terra-time-input/tests/nightwatch/component/TimeInputOnChange.jsx]: lib?

Comment (emilyrohrbough) [inline packages/terra-time-input/tests/nightwatch/component/TimeInputOnChange.jsx]: Oops, had this for quick visual testing.
