### PR TITLE
Move CSS animation to global styles outside of CSS Modules

### LINKED ISSUE #2110: [terra-icon] v2.29.1 breaks animation of loading spinner
# Bug Report

## Description
The latest version of terra-icon broke the animation for the loading spinner in terra-overlay (LoadingOverlay). The issue is not present in 2.29.0.

## Steps to Reproduce
1. Add latest version of terra-overlay (which includes terra-icon 2.29.1 as a dependency) to project.
2. Import LoadingOverlay from terra-overlay.
3. Run project server and render LoadingOverlay.
4. Loading spinner will render but will not show spin animation.

## Additional Context / Screenshots
loading-spinner

## Expected Behavior
The spinner should actually spin.

## Possible Solution
Reverting to 2.29.0 fixes the animation in our app but breaks terra config. @bjankord mentioned a possible solution using css-in-js.

## Environment

* Component Name and Version: terra-icon 2.29.1
* Browser Name and Version: Firefox 63.0.3/Chrome 70.0.3538.110
* Node/npm Version: [e.g. Node 8/npm 5] Node v8.11.1/npm 5.6.0
* Webpack Version: 3.12.0
* Operating System and version (desktop or mobile): macOS 10.13

## @ Mentions
@bjankord @dev-cprice

### PR DESCRIPTION
**Pull request by bjankord**
### Summary
Resolves #2110. This is the third PR we've attemped to fix this. Seeing the the issue seems to occur with config combinitation around CSS Modules and scss-loader, I decided to pull the styles out of CSS Modules parsing altogether for the animation and write them directly to the DOM with the neccessary vendor prefixes. This should work (the animation actually spins the icon) no matter what css-loader / scss-loader config is wired up.

### CODE REVIEW

File: packages/terra-icon/src/IconBase.jsx [hunk 1]
```diff
@@ -50,41 +50,68 @@ const defaultProps = {
...
 
-  // aria-label is present, remove aria-hidden, set role to img
-  if (ariaLabel) {
-    attributes['aria-label'] = ariaLabel;
-    attributes.role = 'img';
-    attributes['aria-hidden'] = null;
-  } else {
-    attributes['aria-hidden'] = 'true';
+    if (isSpin) {
+      const css = '@-webkit-keyframes tui-spin-ltr{0%{-webkit-transform:rotate(0deg);transform:rotate(0deg)}100%{-webkit-transform:rotate(359deg);transform:rotate(359deg)}}@keyframes tui-spin-ltr{0%{-webkit-transform:rotate(0deg);transform:rotate(0deg)}100%{-webkit-transform:rotate(359deg);transform:rotate(359deg)}}@-webkit-keyframes tui-spin-rtl{0%{-webkit-transform:rotate(0deg);transform:rotate(0deg)}100%{-webkit-transform:rotate(-359deg);transform:rotate(-359deg)}}@keyframes tui-spin-rtl{0%{-webkit-transform:rotate(0deg);transform:rotate(0deg)}100%{-webkit-transform:rotate(-359deg);transform:rotate(-359deg)}}[dir=ltr] .tui-Icon.is-spin {-webkit-animation: tui-spin-ltr 2s infinite linear;animation: tui-spin-ltr 2s infinite linear;}[dir=rtl] .tui-Icon.is-spin {-webkit-animation: tui-spin-rtl 2s infinite linear;animation: tui-spin-rtl 2s infinite linear;}';
```
Comment (bjankord) [inline packages/terra-icon/src/IconBase.jsx]: This output is what we see running the styles through autoprefixer currently. I've named spaced the animation name, `tui-spin-ltr` and `tui-spin-rtl` as well as minified the CSS as much as reasonable since we'll write this string inline to the DOM.

File: packages/terra-icon/src/IconBase.jsx [hunk 2]
```diff
@@ -50,41 +50,68 @@ const defaultProps = {
...
-  isSpin,
-  children,
-  height,
-  width,
-  ariaLabel,
-  focusable,
-  ...customProps
-}) => {
-  const attributes = Object.assign({}, customProps);
+class IconBase extends React.Component {
```
Comment (bjankord) [inline packages/terra-icon/src/IconBase.jsx]: Converted this component to class as I was thinking about writing the styles on `componentDidMount` and then opted for writing them to the DOM in the constructor instead.

File: packages/terra-icon/src/IconBase.jsx [hunk 3]
```diff
@@ -50,41 +50,68 @@ const defaultProps = {
...
+      ...customProps
+    } = this.props;
 
-  return <svg {...attributes} className={classes}>{children}</svg>;
-};
+    const attributes = Object.assign({}, customProps);
+
+    // append to existing classNames
+    const classes = cx(
+      'tui-Icon', // Namespaced class since it will be global, needed for global spin animation
```
Comment (bjankord) [inline packages/terra-icon/src/IconBase.jsx]: Global CSS class we use to style the icon with our global CSS animation.

File: packages/terra-icon/src/IconBase.jsx [hunk 4]
```diff
@@ -62,8 +63,25 @@ const IconBase = ({
...
+        style.appendChild(document.createTextNode(css));
+        head.appendChild(style);
+      }
+    }
+  };
+  addAnimationStyles();
+
   // append to existing classNames
   const classes = cx(
+    'tui-Icon',
```
Comment (bjankord) [inline packages/terra-icon/src/IconBase.jsx]: Global CSS class we use to style the icon with our global CSS animation.

**Comment by ChaseSinclair** [comment]
Tested this in my app and it's working as expected.
