### PR TITLE
[Dialog] - Merge custom class name

### LINKED ISSUE #1239: [Dialog] - Merge custom class names
# Issue Description

The dialog component doesn't currently merge custom classes into the default classes. If a custom class is passed in it will overwrite the dialogs default classes. 

https://github.com/cerner/terra-core/blob/master/packages/terra-dialog/src/Dialog.jsx#L37
https://github.com/cerner/terra-core/blob/master/packages/terra-dialog/src/Dialog.jsx#L44

```
<Dialog className="custom-class" />
```
Will result in:
```
<div class="custom-class" />
```
Instead of 
```
<div class="dialog custom-class" />
```

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior

Custom classes should be merged into the dialog classes. 
Example: 
https://github.com/cerner/terra-core/blob/master/packages/terra-divider/src/Divider.jsx#L9-L11
https://github.com/cerner/terra-core/blob/master/packages/terra-divider/src/Divider.jsx#L14

## Current Behavior

Custom classes will override the dialog classNames.

## Steps to Reproduce

1. Create a Dialog.
2. Pass a custom class
3. Observe the dialog class is overwritten by the custom class.

## Environment

* All environments.

### PR DESCRIPTION
**Pull request by saedar**
### Summary
The dialog component doesn't currently merge custom classes into the default classes. If a custom class is passed in it will overwrite the dialogs default classes.

### Additional Details
Closes #1239

### CODE REVIEW

File: packages/terra-dialog/src/Dialog.jsx [hunk 1]
```diff
@@ -37,6 +37,7 @@ const defaultProps = {
 const Dialog = ({ header, footer, onClose, children, ...customProps }) => {
   const dialogClassNames = cx([
     'dialog',
+    customProps.className,
```
Comment (StephenEsser) [inline packages/terra-dialog/src/Dialog.jsx]: This change will also need to reverse the spread order on this line: https://github.com/cerner/terra-core/blob/63f7ece5df3d563a623edff83a79054074264c7d/packages/terra-dialog/src/Dialog.jsx#L48

Otherwise custom classNames will always overwrite dialogClassNames

Comment (saedar) [reply packages/terra-dialog/src/Dialog.jsx]: Thanks for the eyes!

https://github.com/cerner/terra-core/pull/1267/commits/82abfaa85715e73c13b3084555a4c387362cd65f

**Comment by saedar** [comment]
> Let's add a jest test for this. We have this type of test in other components.

@bjankord https://github.com/cerner/terra-core/pull/1267/commits/08c5ce6e139fd4ac698ad0a465656ef5f7a66ca9
