### PR TITLE
Text line height fix

### LINKED ISSUE #1064: Line-height incorrectly inherited in text component
# Issue Description
The line-height in the text component does not correctly apply when a parent element has a larger font-size.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Text component's line height is applied by its font-size, not by parent element font-size

## Current Behavior
Text component's line height is applied by parent if parent sets a different font-size than the one in the text component font-size

### PR DESCRIPTION
**Pull request by jmsv6d**
### Summary
Fixes #1064 
Line height on the text component was getting calculated based on the parent's font size. This is because the line-height is only applies to block level elements. Updated display to be inline-block and went ahead and switched all the tests to wdio since they were simple. 

Please add your name to the [CONTRIBUTORS.md] file. Adding your name to the [CONTRIBUTORS.md] file signifies agreement to all rights and reservations provided by the [License].

Thanks for contributing to Terra. 
@cerner/terra

[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md
[License]: ../blob/master/LICENSE

### CODE REVIEW

File: packages/terra-text/tests/nightwatch/TextLineHeight.jsx [hunk 1]
```diff
@@ -0,0 +1,21 @@
+import React from 'react';
+import Text from '../../lib/Text';
+
+const TextLineHeight = () => (
+  <div>
+    <div style={{ 'font-size': '100px' }}>
```
Comment (JakeLaCombe) [inline packages/terra-text/tests/nightwatch/TextLineHeight.jsx]: Can you do fontSize here?
