### PR TITLE
Show Hide minor fixes

### LINKED ISSUE #1977: Show Hide minor fixes
## Resolve outstanding items from #1956 

- apply correct color fill for icon svg for hover: [#1956comment](https://github.com/cerner/terra-core/pull/1956#pullrequestreview-165288650), focus: [#1956comment](https://github.com/cerner/terra-core/pull/1956#pullrequestreview-165288793), and disabled state [#1956comment](https://github.com/cerner/terra-core/pull/1956#pullrequestreview-165289099)
- correct icon with multi-line wrapping, should be vertically centered (most likely need to change display to inline-block) 
- minor button sizing changes for when text wraps (need to reduce value for line-height `1.429` to and increase padding to `0.21428rem  0`, to keep touch-friendly size)
- adding new test for long button text w/wrapping label
- fix test for showing the states (normal,hover,focus,active,disabled)

\
also was discussed:
- possibly update variable names for `--terra-show-hide-button-icon` to `--terra-show-hide-button-background-image` to follow newly proposed linting rules.

### PR DESCRIPTION
**Pull request by bjankord**
### Summary
Resolves #1977

### CODE REVIEW

File: packages/terra-show-hide/src/_ShowHideButton.jsx [hunk 1]
```diff
@@ -50,16 +42,10 @@ const propTypes = {
    * Sets the button text.
    */
   text: PropTypes.string.isRequired,
-  /**
-   * Sets the button type. One of `button`, `submit`, or `reset`.
-   */
-  type: PropTypes.oneOf([ButtonTypes.BUTTON, ButtonTypes.SUBMIT, ButtonTypes.RESET]),
```
Comment (bjankord) [inline packages/terra-show-hide/src/_ShowHideButton.jsx]: This button will only be `type="button"`, we can get rid of the other types.

File: packages/terra-show-hide/src/_ShowHideButton.jsx [hunk 2]
```diff
@@ -13,15 +13,7 @@ const KEYCODES = {
...
 
-const ButtonTypes = {
-  BUTTON: 'button',
-};
-
 const propTypes = {
-  /**
-   * Whether or not the button should be disabled.
-   */
-  isDisabled: PropTypes.bool,
```
Comment (bjankord) [inline packages/terra-show-hide/src/_ShowHideButton.jsx]: UX has specified that this button should not be able to be disabled.

File: packages/terra-show-hide/src/_ShowHideButton.module.scss [hunk 3]
```diff
@@ -14,10 +9,7 @@
   // https://github.com/necolas/normalize.css/issues/566
   // https://github.com/necolas/normalize.css/commit/1be44f3b2a79af5d463c7ea0264fee0e6fa464ca
   // stylelint-disable selector-no-qualifying-type
-  button.button,
-  html input[type='button'].button,
-  input[type='reset'].button,
-  input[type='submit'].button {
```
Comment (bjankord) [inline packages/terra-show-hide/src/_ShowHideButton.module.scss]: Since we only need `button[type="button"]`, we can get rid of some of the normalize styles.

File: packages/terra-show-hide/src/_ShowHideButton.jsx [hunk 4]
```diff
@@ -135,18 +118,22 @@ class Button extends React.Component {
...
+        type="button"
         onKeyDown={this.handleKeyDown}
         onKeyUp={this.handleKeyUp}
         onBlur={this.handleOnBlur}
         onClick={onClick}
         onFocus={onFocus}
         ref={refCallback}
       >
-        {text}
+        <span className={cx('inner')}>
```
Comment (bjankord) [inline packages/terra-show-hide/src/_ShowHideButton.jsx]: Using flexbox to vertically center align icon when text wraps. Button can't be `display: flex` in some browsers so using inner spans to set up flexbox.

File: packages/terra-show-hide/src/terra-dev-site/test/show-hide/StatesShowHide.test.jsx [hunk 5]
```diff
@@ -1,30 +0,0 @@
-import React from 'react';
-import ShowHide from '../../../ShowHide';
-
-const StatesShowHideTest = () => (
```
Comment (bjankord) [inline packages/terra-show-hide/src/terra-dev-site/test/show-hide/StatesShowHide.test.jsx]: This file is no longer needed, the focus, hover, and active states are tested by hitting the default test example and using the click events, keyEvents, and mouse emulation in the wdio test to trigger the various states.

File: packages/terra-show-hide/src/_ShowHideButton.module.scss [hunk 6]
```diff
@@ -30,11 +22,11 @@
     display: inline-block; // prevents variant icon from breaking onto its own line
     font-family: inherit;
     font-size: var(--terra-show-hide-button-font-size, 1rem);
-    line-height: var(--terra-show-hide-button-line-height, 1.85714);
+    line-height: var(--terra-show-hide-button-line-height, 1.429);
     outline: none;
-    padding: 0;
+    padding: 0.21428rem 0;
```
Comment (neilpfeiffer) [inline packages/terra-show-hide/src/_ShowHideButton.module.scss]: Lets add theming variable for padding.

**Comment by neilpfeiffer** [comment]
Nit: Not a major issue but tests & evidence reference left/right (fine for center) in file name/test name instead of start/end (standing out in RTL testing):
ButtonAlignLeftShowHide.test.jsx
ButtonAlignRightShowHide.test.jsx

**Comment by neilpfeiffer** [comment]
Tested: PR #1956
 
 
**Reviewed:**
- Resolved all items specified in Issue #1977 from initial validation of PR #1956




\
\
Verified by @neilpfeiffer Ready for Release.
 
 
**Pass** |
-----------|
UX Review|
