### PR TITLE
Button onfocus

### LINKED ISSUE #2688: [terra-button] DST Clarification Button does not take focus in Safari/Firefox
# Bug Report

## Description
In Safari and Firefox, clicking the time clarification button from a DST workflow for the terra-date-time-picker and then selecting a timezone does not return focus to the clarification button, nor does it invoke the consumer provided onBlur prop. This is particularly troublesome when that onBlur prop how the updates to the date time value get applied.

## Steps to Reproduce
1. Navigate to https://engineering.cerner.com/terra-ui/components/terra-date-time-picker/date-time-picker/date-time-picker in firefox or safari
2. Enter the ambiguous hour (e.g., 11/03/2019, 1:22) - modal appears, clarify your time
3. Modal disappears, click clarification button, modal reappears. Select opposite time, notice no button highlighting (terra-button 3.20.0 fixed how the button would be highlighted in chrome in this workflow, in firefox/safari it's not just that it's not highlighted, it does not even have focus)
4. If you like, run the workflow in chrome and observe the difference

## Additional Context / Screenshots
I think this is an issue with the terra-button and the fixes around programmatic focus being browser dependent, which is why I logged it here. If my assumption is wrong I apologize and this may be a terra-date-time-picker issue.
https://jira2.cerner.com/browse/ORDPLANDEV-29226 has video

## Expected Behavior
Either for the button to have focus after the modal closes (after being launched from the button), or for the provided onBlur method to be invoked.

## Possible Solution
Right now I know the date-time-picker attempts to put focus back on the button as that is where it was before the modal was launched. If that behavior isn't necessary, just invoking the onBlur method of the consumer upon the modal being dismissed would work for us... but the correct fix is probably getting focus set on the button.

## @ Mentions
@benbcai @dev-cprice  @mjhenkes

### PR DESCRIPTION
**Pull request by benbcai**
### Summary
Fixes #2688, #1969 

### Additional Details
Clicking on a button does not get focused on Firefox, Safari, and IE. Hence, clicking away from it does not trigger onBlur, causing the issue on #2688. This PR sets the focus on the button when clicked.

### CODE REVIEW

File: packages/terra-button/src/Button.jsx [hunk 1]
```diff
@@ -133,6 +134,19 @@ class Button extends React.Component {
     }
   }
 
+  handleClick(event) {
```
Comment (supreethmr) [inline packages/terra-button/src/Button.jsx]: I assume this issue  of focus not shifting back to button in Safari and FireFox was due to button not being set as [previouslyFocusedElement](https://github.com/davidtheclark/focus-trap-react/blob/e67d26c5ff512228007bd6eb55aea9841eb7e09d/src/focus-trap-react.js#L10) in focus-trap and instead `main` element was being updated as previouslyFocusedElement. 

So Curious to know to keep button as active element and so that it gets updated as [previouslyFocusedElement](https://github.com/davidtheclark/focus-trap-react/blob/e67d26c5ff512228007bd6eb55aea9841eb7e09d/src/focus-trap-react.js#L10) when popup opens. do we need handleClick() event OR can we just set the focus to button on handleMouseDown() event like below.
```javascript
  handleMouseDown(event) {
    this.shouldShowFocus = false;
    setTimeout(() => { this.shouldShowFocus = true; });

    if (this.props.onMouseDown) {
      this.props.onMouseDown(event);
    }

    event.preventDefault();
    event.currentTarget.focus();
  }
```

Comment (benbcai) [reply packages/terra-button/src/Button.jsx]: @supreethmr The issue is that in FF, Safari, and IE when you click on the button, it does not trigger the onFocus event like it does in Chrome. Since it didn't become focused after clicked, clicked outside would also not trigger the onBlur event, which causes the issue reported on #2688. Clicking and focus on a button varies by browser and OS. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Button#Clicking_and_focus. 

This change is to set the focus on the button when clicked. The mouseDown event is triggered on both left and right mouse click but the focus should only be set on the button being clicked. Hence, I need to do that in handleClick.

Comment (supreethmr) [reply packages/terra-button/src/Button.jsx]: Got it Thank you @benbcai  for the info.

File: packages/terra-button/src/Button.jsx [hunk 2]
```diff
@@ -186,11 +200,16 @@ class Button extends React.Component {
     // Prevent button from showing focus styles when clicked
     this.shouldShowFocus = false;
     // Wait until after onFocus has been triggered on browsers where it will get triggered for click
-    setTimeout(() => { this.shouldShowFocus = true; });
+    setTimeout(() => { this.shouldShowFocus = true; }, 300);
```
Comment (yuderekyu) [inline packages/terra-button/src/Button.jsx]: just curious, does this still work without setting  `300` inside the timeout?

Comment (benbcai) [reply packages/terra-button/src/Button.jsx]: handkeKeyDown is called before handleClick above to put focus on the button. Since we don't want focus glow when clicking we need to wait until onclick is triggered before setting shouldShowFocus back to true.
