### PR TITLE
[terra-form-select] Fix to keep focus on select on pressing escape to close dropdown.

### LINKED ISSUE #3109: [Terra-form-select] Focus should remain on select when ESC button is pressed and dropdown is open.
Focus should remain on select when dropdown is open and ESC button is pressed . this issue exists in Select and Single select variants.  This is working fine in other variants like Multiple and Tag.

## Steps to Reproduce
1.  Navigate to [default example](https://engineering.cerner.com/terra-ui/components/terra-form-select/form-select/select)
2.  Click on the toggle button. observe that dropdown opens.
3.  Press ESC button.
4.  Observe focus does not remains on select.

Select Variant ESC Press

## Expected Behavior
Focus should remain on select.

### PR DESCRIPTION
**Pull request by saket2403**
### Summary
Fixed issue to keep focus on select (single-variant) on pressing escape to close dropdown.

Closes #3109 

### Deployment Link

https://terra-core-deployed-pr-#.herokuapp.com/

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

File: packages/terra-form-select/src/single/Frame.jsx [hunk 1]
```diff
@@ -317,6 +317,7 @@ class Frame extends React.Component {
       event.preventDefault();
       this.openDropdown();
     } else if (keyCode === KeyCode.KEY_ESCAPE) {
+      this.select.focus();
```
Comment (supreethmr) [inline packages/terra-form-select/src/single/Frame.jsx:320]: was it happening only on single select...???

Comment (saket2403) [reply packages/terra-form-select/src/single/Frame.jsx:320]: Yes

**Comment by PaulSolDev** [comment]
Functional review complete. No issues identified.
