### PR TITLE
Paginator a11y update

### LINKED ISSUE #1635: Progressive Paginator has 508 and WCAG2AA a11y violations at collapsed mobile view
# Bug Report

## Description

There are 508 and WCAG2AA a11y violations for the Progressive Paginator at the collapsed mobile view.

pp-508
pp-508-2
pp-wcag2aa
pp-wcag2aa-2

## Steps to Reproduce

1. Navigate to the progressive paginator on the [doc site](https://engineering.cerner.com/terra-core/#/components/terra-paginator/paginator/progressive-paginator)
2. Set the window size to small enough so that the progressive paginator looks like the following:

screen shot 2018-06-22 at 12 10 24 pm

3. Open up the [HTML CodeSniffer](https://squizlabs.github.io/HTML_CodeSniffer/).
4. Set the code sniffer filter to Section 508, observe the two a11y errors. 
5. Set the code sniffer filter to WCAG2AA, observe the four a11y errors.

## Expected Behavior

No a11y violations.

## Environment

* Component Name and Version: terra-paginator 1.5.0
* Browser Name and Version: all browsers
* Node/npm Version: node v8.11.2, npm v6.1.0
* Webpack Version: 
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by bjankord**
### Summary
Resolves #1635

### CODE REVIEW

File: packages/terra-paginator/src/ControlledPaginator.jsx [hunk 1]
```diff
@@ -202,6 +202,7 @@ class Paginator extends React.Component {
           onClick={this.handlePageChange(previousPageIndex)}
           onKeyDown={this.handleOnKeyDown(previousPageIndex)}
         >
+          <span className={cx('visually-hidden')}>Previous</span>
```
Comment (emilyrohrbough) [inline packages/terra-paginator/src/ControlledPaginator.jsx]: Action-header has the translations for Previous and Next. Can we add the internationalization for these? https://github.com/cerner/terra-core/blob/master/packages/terra-action-header/translations/en-GB.json#L4

Comment (bjankord) [reply packages/terra-paginator/src/ControlledPaginator.jsx]: Translations will be added in a follow-up PR to resolve #1493
