### PR TITLE
[terra-profile-image] Update fallback image styles.

### LINKED ISSUE #3432: [terra-profile-image] fallback image missing equal style and treatments as valid image
# Bug Report

## Description

When Terra-profile-image has a correct/successful image source, it does not have the same treatment applied for when it has an invalid/unsuccessful image source.  There should be parity in approach between the regular profile-image and the fallback/placeholder that is built in.

## Additional Context / Screenshots

Attaching a series of example tests, testing with a valid src image (e.g. `src={exampleProfileImage}`) on the left, next to an invalid src image (e.g. `src="invalid.jpg"`) on the right. The expected is for the fallback placeholder to be the same but with a replacement image.

1: when two images are side-by-side, both should be inline and vertically-aligned to the middle:
```
<ProfileImage width="75" height="75" alt="inline test" src={exampleProfileImage} />
<ProfileImage width="75" height="75" alt="inline test" src="invalid.jpg" />
```
1-inline
\
\
\
2: When adding additional CSS Style, the fallback image doesn't also apply the style
```
<ProfileImage width="75" height="75" className={cx('test-style-border')} alt="adds css style" src={exampleProfileImage} />
<ProfileImage width="75" height="75" className={cx('test-style-border')} alt="adds css style" src="invalid.jpg" />
```
```
.test-style-border {
    border: 10px solid rgb(69, 221, 170);
    border-radius: 25px;
    box-sizing: content-box;
}
```
2-style
\
\
\
3: When Height and Width is not provided via props, the fallback image doesn't appear, should rely on a default image size
 ```
 <ProfileImage alt="no height or width provided" src={exampleProfileImage} />
 <ProfileImage alt="no height or width provided" src="invalid.jpg" />
 ```
3-no-height-width
\
\
\
4. When Height and Width are provided by CSS and not props, the fallback image doesn't appear, should use css size
```
<ProfileImage className={cx('test-style-size')} alt="use css size instead" src={exampleProfileImage} />
<ProfileImage className={cx('test-style-size')} alt="use css size instead" src="invalid.jpg" />
```
```
.test-style-size {
    height: 100px;
    width: 40px;
}
```
4-height-width-css
\
\
\
5. Profile-Image implements Terra-Image, and though it's not declared, allows for the passthrough of Terra-Image props like variant, which are not applied to the fallback image
```
<ProfileImage width="75" height="75" alt="passing through terra-image props" src={exampleProfileImage} variant="thumbnail" />
<ProfileImage width="75" height="75" alt="passing through terra-image props" src="invalid.jpg" variant="thumbnail" />
<ProfileImage width="75" height="75" alt="passing through terra-image props" src={exampleProfileImage} variant="circle" />
<ProfileImage width="75" height="75" alt="passing through terra-image props" src="invalid.jpg" variant="circle" />
```
5-image-variants
\
\
\
6. The same Fit treatment should also apply to the fallback image when set
```
<ProfileImage width="75" height="150" alt="testing fit" src={exampleProfileImage} fit="contain" />
<ProfileImage width="75" height="150" alt="testing fit" src="invalid.jpg" fit="contain" />
<ProfileImage width="150" height="75" alt="testing fit" src={exampleProfileImage} fit="scale-down" />
<ProfileImage width="150" height="75" alt="testing fit" src="invalid.jpg" fit="scale-down" />
```
6-image-fit

## @ Mentions

followup to PR #3422 and issue #3412

### PR DESCRIPTION
**Pull request by pranav300**
### Summary

This PR updates fallback image styles. So, that they are visually similar to valid images.

Closes #3432 

### Deployment Link

- docs: https://terra-core-update-fallb-szp8mb.herokuapp.com/components/terra-profile-image/profile-image/profile-image
- tests: https://terra-core-update-fallb-szp8mb.herokuapp.com/tests/terra-profile-image/profile-image/profile-image-default

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

**Comment by neilpfeiffer** [comment]
UX +1 to fix #3432

**Review by mjhenkes — APPROVED** [review]

File: packages/terra-profile-image/src/ProfileImage.jsx [hunk 1]
```diff
@@ -42,30 +50,71 @@ const propTypes = {
...
+      fit,
+      variant,
+      theme.className,
+    ]),
+    customProps.className,
+  );
 
   /* eslint-disable react/forbid-dom-props */
-  const placeholderImage = (
+  const ProfileImagePlaceholder = (
```
Comment (tbiethman) [inline packages/terra-profile-image/src/ProfileImage.jsx:82]: I'd keep the leading p lowercase, as this isn't defining a component.

**Review by tbiethman — APPROVED** [review]

File: packages/terra-profile-image/src/ProfileImage.jsx (hunk 1 above)
Comment (neilpfeiffer) [reply packages/terra-profile-image/src/ProfileImage.jsx]: Updated: https://github.com/cerner/terra-core/pull/3461/commits/a3817dcd871a7d18ab7ebd20bf5f9141273e5f40

**Review by benbcai — APPROVED** [review]

**Review by ShettyAkarsh — APPROVED** [review]
