### PR TITLE
[terra-status-view] Move overflow from inner to outer div

### LINKED ISSUE #3383: [terra-status-view] move overflow to outermost div
# Bug Report
Presenting a themed status view in non constrained height might result in a scrollbar, because of theme values like font-size and line-height. Instead, the status-view should account for the upper and lower portions of space before triggering overflow. 

A proposed fix is moving `overflow: auto` from the "inner content" div to the outer most div. From [here](https://github.com/cerner/terra-core/blob/main/packages/terra-status-view/src/StatusView.module.scss#L43) to [here](https://github.com/cerner/terra-core/blob/main/packages/terra-status-view/src/StatusView.module.scss#L9). Let's also add a validation to verify that overflow behaves as expected at a small height.

Current themed example on Chrome: Screen Shot 2021-02-22 at 1 13 31 PM

Proposed Fix: Screen Shot 2021-02-22 at 1 26 06 PM

Proposed Fix presenting the status-view in a 100px height container:
Screen Shot 2021-02-22 at 1 17 26 PM

### PR DESCRIPTION
**Pull request by pranav300**
### Summary

This PR replaces style `overflow: auto;` from `innerView` to `outerView`.

Closes #3383 

### Deployment Link

https://terra-core-deployed-pr-#.herokuapp.com/

### Testing

Added a new test file and wdio test to validate these changes.

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

File: packages/terra-status-view/tests/wdio/status-view-spec.js [hunk 1]
```diff
@@ -40,4 +40,12 @@ Terra.describeViewports('StatusView', ['medium'], () => {
     browser.url('/raw/tests/terra-status-view/status-view/status-view-thin-constraint');
     Terra.validates.element('error too thin for glyph');
   });
+  it('Displays scrolled Status View', () => {
+    browser.url('/raw/tests/terra-status-view/status-view/status-view-overflow');
+    // eslint-disable-next-line prefer-arrow-callback
+    browser.execute(function scrollOptionIntoView() {
+      document.querySelector('p[class*="title"]').scrollIntoView();
+    });
+    Terra.validates.element('scrolled', { selector: '#root' });
```
Comment (yuderekyu) [inline packages/terra-status-view/tests/wdio/status-view-spec.js:49]: can we use the test component's id for the screenshot instead? i'd rather have a screenshot of the component itself, not the whole page

File: packages/terra-status-view/CHANGELOG.md [hunk 2]
```diff
@@ -2,6 +2,9 @@
 
 ## Unreleased
 
+* Changed
```
Comment (StephenEsser) [inline packages/terra-status-view/CHANGELOG.md:5]:
```suggestion
* Fixed
```

Since this is a bug fix we'll want to group it in a fixed section.

File: packages/terra-status-view/CHANGELOG.md [hunk 3]
```diff
@@ -2,6 +2,9 @@
...
+  * Replaced style `overflow: auto;` from `innerView` to `outerView`.
```
Comment (StephenEsser) [inline packages/terra-status-view/CHANGELOG.md:6]: This should describe what was broken/fixed. 

Something like:

> Fix glyph scrollbar appearing when there is enough room to display

Comment (pranav300) [reply packages/terra-status-view/CHANGELOG.md]: Updated here https://github.com/cerner/terra-core/pull/3392/commits/b960ae6e215b94422d0db6eb5ec69289524df161.

File: packages/terra-status-view/tests/wdio/status-view-spec.js (hunk 1 above)
Comment (pranav300) [reply packages/terra-status-view/tests/wdio/status-view-spec.js]: Updated here https://github.com/cerner/terra-core/pull/3392/commits/b960ae6e215b94422d0db6eb5ec69289524df161.

**Review by supreethmr — APPROVED** [review]

File: packages/terra-status-view/tests/wdio/status-view-spec.js [hunk 4]
```diff
@@ -40,4 +40,12 @@ Terra.describeViewports('StatusView', ['medium'], () => {
     browser.url('/raw/tests/terra-status-view/status-view/status-view-thin-constraint');
     Terra.validates.element('error too thin for glyph');
   });
+  it('Displays scrolled Status View', () => {
```
Comment (yuderekyu) [inline packages/terra-status-view/tests/wdio/status-view-spec.js:43]:
```suggestion
  it('Overflows correctly when the container height is constrained', () => {
```

**Review by yuderekyu — APPROVED** [review]

**Review by benbcai — APPROVED** [review]

**Review by ShettyAkarsh — APPROVED** [review]

File: packages/terra-status-view/tests/wdio/status-view-spec.js [hunk 5]
```diff
@@ -40,4 +40,12 @@ Terra.describeViewports('StatusView', ['medium'], () => {
     browser.url('/raw/tests/terra-status-view/status-view/status-view-thin-constraint');
     Terra.validates.element('error too thin for glyph');
   });
+  it('Overflows correctly when the container height is constrained', () => {
+    browser.url('/raw/tests/terra-status-view/status-view/status-view-overflow');
+    // eslint-disable-next-line prefer-arrow-callback
+    browser.execute(function scrollOptionIntoView() {
```
Comment (yuderekyu) [inline packages/terra-status-view/tests/wdio/status-view-spec.js:46]: can we use wdio's hook instead? https://v6.webdriver.io/docs/api/element/scrollIntoView.html

also, i'm curious what happens if we don't have this, is the component initially scrolled to the top?

**Review by StephenEsser — APPROVED** [review]

File: packages/terra-status-view/tests/wdio/status-view-spec.js (hunk 5 above)
Comment (pranav300) [reply packages/terra-status-view/tests/wdio/status-view-spec.js]: Updated here https://github.com/cerner/terra-core/pull/3392/commits/b4f4e487f42787a0c74eb96565a4e1df7e99a710

**Review by lokesh-0813 — APPROVED** [review]

**Review by neilpfeiffer — APPROVED** [review]
Tested: PR #3392
Resolves: Issue #3383

**Reviewed:**
- moves overflow without any apparent negative effects

**UX Reviewed** |
-----------|
